server:
  port: 9330 #端口
# 数据库访问配置
spring:
  application:
    name: dev-manager
  datasource:
    # 配置数据源类型
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.99.120.252:13001/spjc?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&useSSL=false
    username: jc
    password: 123456
    #url: jdbc:mysql://localhost:3306/mybatis?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&useSSL=false
    #username: root
    #password: root
    # 初始化，最小，最大连接数
    initialSize: 3
    minidle: 3
    maxActive: 18
    # 获取数据库连接等待的超时时间
    maxWait: 60000
    # 配置多久进行一次检测，检测需要关闭的空闲连接 单位毫秒
    timeBetweenEvictionRunsMillis: 60000
    validationQuery: SELECT 1 FROM dual
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.sanz.workbench.model
#mybatis-plus:
#  mapper-locations: classpath*:/mapping/*.xml
#  typeAliasesPackage: cn.gov.nbfsi.fsi.rest.modular.api.model;cn.gov.nbfsi.fsi.rest.modular.system.model;
#   cn.gov.nbfsi.fsi.rest.modular.api.entity.dto;cn.gov.nbfsi.fsi.rest.modular.datav.dto;
#  global-config:
#    id-type: 0  #0:数据库ID自增   1:用户输入id  2:全局唯一id(IdWorker)  3:全局唯一ID(uuid)
#    db-column-underline: false
#    refresh-mapper: true
#  configuration:
#    map-underscore-to-camel-case: false
#    cache-enabled: true #配置的缓存的全局开关
#    lazyLoadingEnabled: true #延时加载的开关
#    multipleResultSetsEnabled: true #开启的话，延时加载一个属性时会加载该对象全部属性，否则按需加载属性

